### ISSUE TITLE
Angry bird was better

### ISSUE THREAD

**Issue by RyanHolmes** [ellisonleao/clumsy-bird#57]
Your code is deprecated.

**Comment by codex8** [comment]
@RyanHolmes this is up to us how we can make it better

**Comment by ellisonleao** [comment]
Not sure if i understand this issue. Can you explain it, please?

**Comment by Brunobinch** [comment]
Hello

Sorry It was mistake. Just test

Greetings from Brunobinch Alias Markus P.

2015-02-05 17:19 GMT+02:00 Ellison Leão <notifications@github.com>:

**Comment by ellisonleao** [comment]
:+1:
