### ISSUE TITLE
Bird slowly leaving render screen

### ISSUE THREAD

**Issue by InDieTasten** [ellisonleao/clumsy-bird#60]
The bird starts out at a certain position (about a 10th of the screen width) away from the left border. But the scrolling speed is faster than the actual bird, resulting in the bird getting closer and closer to the border and finally be completely out of screen after about 30 "steps" of score

**Comment by ellisonleao** [comment]
hmm, i will test this behaviour ASAP. Thanks for the feedback!

**Comment by ellisonleao** [comment]
Just for the record @InDieTasten , what browser are you testing it?

**Comment by InDieTasten** [comment]
Google Chrome, maximized window at 1600x900 monitor resolution

**Comment by ellisonleao** [comment]
Hey @InDieTasten , i just fixed the issue. Can you try again please?

**Comment by InDieTasten** [comment]
:+1: I will ;)

**Comment by InDieTasten** [comment]
![flappyprove](https://cloud.githubusercontent.com/assets/7047377/6561384/400252a0-c691-11e4-9264-d35d4c31e36e.PNG)
:star:

**Comment by ellisonleao** [comment]
:+1: nice!
