### ISSUE TITLE
Update to melonJS 2.1

### ISSUE THREAD

**Issue by ellisonleao** [ellisonleao/clumsy-bird#63]

**Comment by RUPOJS** [comment]
Hi @ellisonleao 
is it still open? If it is, can you please provide some description as I wanted to send a PR.

**Comment by ellisonleao** [comment]
Hey @RUPOJS , basically we need to update the code to the latest changes in melonJS 2.1. There is a blog post here http://blog.ciangames.com/2015/05/upgrading-to-melonjs-21.html

**Comment by TLDuys** [comment]
Why is this send to me ?

2015-07-01 17:47 GMT+02:00 Ellison Leão <notifications@github.com>:
