### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by rarhs** [ellisonleao/clumsy-bird#68]
Whenever I click the heroku button I ended up with message like this: `couldn't find the source blob.`
Can you show a way to get rid of this?

**Comment by ellisonleao** [comment]
Hey @rarhs sorry for the late reply. From what i've seen this is a heroku issue, and you just have to keep trying to deploy it.  I don't have any extra thoughts about it. Probably it's just best to add it on your web server.

**Comment by ellisonleao** [comment]
Nevermind, this was one issue with the wrong branch being called on the heroku button. It's fixed now. Thanks for the feedback.
