### ISSUE TITLE
Issue with bird going off the screen on the left.

### ISSUE THREAD

**Issue by KL2CRT** [ellisonleao/clumsy-bird#69]
bird falls off the screen.

![birdy](https://cloud.githubusercontent.com/assets/22793490/20140319/639247e8-a682-11e6-9798-b455c826ade0.png)

**Comment by ellisonleao** [comment]
Thanks @KL2CRT  i will take a look on this ASAP

**Comment by KL2CRT** [comment]
OK can you keep me updated with your progress thank you

**Comment by ellisonleao** [comment]
Fixed on latest upgrade. Thanks for the feedback @KL2CRT !
