### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by mattymoo98** [ellisonleao/clumsy-bird#71]
the program will open in google chrome but not internet explorer.
![capture4](https://cloud.githubusercontent.com/assets/22790968/20859489/bd3db230-b958-11e6-86f9-06baf4b50f95.PNG)

**Comment by ellisonleao** [comment]
Hey @mattymoo98 what IE version are you using?

**Comment by obiot** [comment]
works for me under IE11, using the latest master version.  

IMHO, if IE10<=, who cares anyway ?

**Comment by ellisonleao** [comment]
closing
